INSERT INTO Fragrances(dior,original,dupe) VALUES
('24','24 Gold','Rhagba, Lattafa'),
('Abercrombie & Fitch','Fierce (Women)','Edition One, Armaf'),
('Abercrombie & Fitch','Fierce (Men)','Derby Club House Gold, Armaf'),
('Alexandre.J','Morning Mucs','Modern Musk, Maison Alhambra'),
('Alina Corel','Jessy','Brown Orchid Gold, Fragrance World'),
('Amouage','Epic Man','Faqat Lil Rijal, Rasasi'),
('Amouage','Interlude Man','Midnite Oud, Out Al Zaafaran Dahn Al Oud Amiri EDP Shaghaf Oud Abyad, Swiss Arabian Evolution, Zimaya Black Oudh, Orientica'),
('Amouage','Guidance','Bayn Al Asrar EDP, Paris Corner Decadent Dream, Maison Alhambra'),
('Amouage','Crimson Rocks','Abraaj Carmine, FA Paris'),
('Amouage','Blossom Love','Junoon Rose, Al Haramain'),
('Amouage','Memoir','Optus VII, Maison Alhambra'),
('Amouage','Interlude','Ethnic Oud, Maison Alhambra'),
('Amouage','Epic','Icon, Zimaya'),
('Amouage','Bracken Man','Abraaj Brackish, Fragrance World'),
('Amouage','Royal Tobacco','Jabal Al Lawz, Arabian Oud Charuto Regal Reserve, Paris Corner'),
('Amouage','Opus V','Roman V, Maison Alhambra'),
('Amouage','Opus VII','Roman Optus VII, Maison Alhambra'),
('Amouage','Reflection Man','Only Black, Arabian Oud Mystique Homme, Al Haramain Khadlaj Shiyaaka for Men, Khadlaj'),
('Amouage','Gold Man','Brulant Oud, Maison Alhambra'),
('Amouage','Beach Hut Man','Killer Oud Cabana, Paris Corner'),
('Amouage','Rose Incense','Posh Alpha, Fragrance World'),
('Amouage','Beloved Man','Derby Club House, Armaf'),
('Armani','Rose D Arabie','Rose D Prive, French Avenue, Fragrance World Velvet Rose, Lattafa Private Army Rose Arabia, Fragrance World'),
('Armani','Acqua Di Gio (MEN)','Jorge Di Profumo, Maison Alhambra Aqua de Classic Pour Homme, Fragrance World Aquarino H for Men, Dubai Essences'),
('Armani','Stronger with You','Your Touch, Maison Alhambra Florida, Al Rehab Proud of You Absolute, Fragrance World'),
('Armani','Code Profumo','Hyaati Gold, Lattafa'),
('Armani','Stronger With You Amber','Proud of You Amber, Fragrance World'),
('Armani','Stronger With You Oud','Veteran Oud, Pendora Scents'),
('Armani','Si','Watani, Al Wataniah Pretty in Pink, Rayhaan'),
('Armani','Armani Code','Harmony Code, Fragrance World'),
('Armani','Armani Code EDP','Harmony Code Intense, Fragrance World'),
('Armani','Armani Code Absolu','Harmony Code Absolute, Fragrance World'),
('Armani','Armani Eau De Nuit','Giorgio Black Special Edition II, Fragrance World'),
('Armani','My Way','La Voie, Maison Alhambra 9AM, Afnan UR WAY, Fragrance World'),
('Armani','My Way Intense','UR WAY Intense, Fragrance World'),
('Armani Prive','Rouge Malachite','Afaq, Lattafa  Niche Royal Rouge, Maison Alhambra'),
('Armani Prive','Indigo Tanzanite','Athoor Al Alam Euyuni, Fragrance World'),
('Armani Prive','Magenta Tanzanite','Athoor Al Alam Zakariyat Luxe, Fragrance World'),
('Armani Prive','Rose D arabie','Velvet Rose, Lattafa'),
('Armani Prive','Oud Royal','Opulent Oud, Lattafa'),
('Atelier des Ors','Larmes du Desert','Arabian Incense, Fragrance World, Artisan Collection'),
('Azzaro','The Most Wanted','Ansaam Silver, Lattafa Intense Wayfarer, Paris Corner Men More Intense, Dubai Essences'),
('Azzaro','Chrome Legend','Italiano Uomo, Armaf'),
('Bath & Body Works','Mahogany','Hard Wood, Fragrance World'),
('BDK','Gris Charnel','Francique 63.55, French Avenue, Fragrance World Liam Grey, Lataffa'),
('BDK','Creme de Cuir','Meringue, Fragrance World'),
('BDK','Velvet Tonka','Shaghaf Oud Tonka, Swiss Arabian Velvety Tonka, Rogue Perfumes'),
('BDK','Rouge Smoking','Rouge Mystique, Rogue Perfumes Francique 107.9, French Avenue, Fragrance World'),
('BDK','Tabac Rose','Tobacco Rose, Rogue Perfumes'),
('Bentley','Bentley for Men Black Edition','Man Black Edition, Maison Alhambra'),
('Billy Eilish','Eilish','Nebras, Lattafa Ophidian Sweet Surrender, Paris Corner'),
('Boadicea The Victorious','Valiant','Hawa, Swiss Arabian '),
('Boadicea The Victorious','Blue Sapphire','La Peregrina, Ayaam'),
('Boadicea The Victorious','Green Sapphire','Green Sapphire, Fragrance World'),
('Boadicea The Victorious','Violet Sapphire','Violet Sapphire, Fragrance World'),
('Boadicea The Victorious','Hero','Mocha Wood, Fragrance World'),
('BOHOBOCO','Red Wine Brown Sugar','Artisan Perfume Brown Sugar, Fragrance World'),
('Boka Boka','Wet Cherry Liquor','Cherry Blush, Nuha'),
('Bond No.9','Lafayette Street','Avenue New York, Grandeur Rock Street, Emper Game of Spades Wild Card, Jo Milano Z6, Zakat'),
('Bond No.9','Greenwich Village','Avenue London, Grandeur Luxe Journey, Maison Alhambra Z9, Zakat Green Valley Village, Emper'),
('Bond No.9','New York Nights','Z7, Zakat Metropolis Night Party, Emer Luxe Night, Maison Alhambra'),
('Bond No.9','Nolita','Luxe Chic, Maison Alhambra Z19 Lolita, Zakat Metropolis Hot Lips, Emer'),
('Bond No.9','TriBeCa','Luxe Blanc, Maison Alhambra'),
('Bond No.9','Bond No.9','Metropolis Gold, Emper'),
('Bond No.9','B9','Z33, Zakat'),
('Bond No.9','Madison Square Park','Z39, Zakat'),
('Bond No.9','Bleecker St','Z25, Zakat'),
('Bond No.9','I Love NY','The Warrior, Armaf'),
('Bond No.9','Gold','Z15, Zakat'),
('Borntostandout','Sugar Addict','Artisan Ethnique, Lattafa'),
('Burberry','My Burberry Black','My Boutique, Pendora Scents My Boutique, Paris Corner'),
('Burberry','Goddess','Athena, Maison Alhambra'),
('Burberry','Mr Burberry','Club de Nuit Urban Man, Armaf'),
('Burberry','Her Elixir','White Forest Strawberry, Khadlaj'),
('Burberry','Her','Rave Now Women, Lattafa Shiyaaka Rose Gold, Khadlaj'),
('Bvlgari','La Gemme Kobraa','Vie Sol, French Avenue, Fragrance World'),
('Bvlgari','Le Gemme Orom','Sceptre Oceana, Maison Alhambra'),
('Bvlgari','Le Gemme Onekh','Vie Brise, French Avenue, Fragrance World'),
('Bvlgari','Le Gemme Azaran','Vie Feu, French Avenue, Fragrance World'),
('Bvlgari','Kobraa','Nashwa Oud, Arabiyat Prestige'),
('Bvlgari','Bvlgari','Turathi Blue, Afnan Al Qiam Silver (Pride Edition), Lattafa Al Qiam Silver, Lattafa Junoon Oud, Al Haramain Stellar Musk, Khadlaj Kaaf, Ahmed Al Maghribi Aariz, Arabiyat Prestige Empire Crown, Khadlaj UN I, North Stag Expressions Vie Ciel, French Avenue, Fragrance World'),
('Bvlgari','Aqva Pour Homme','Aquilo Pour Homme, Maison Alhambra Bavaria Pour Homme, Fragrance World'),
('Bvlgari','Man','Extra Woods, Maison Alhambra'),
('Bvlgari','Man in Black','Bavaria Man Intense, Fragrance World Signature Night, Armaf'),
('Bvlgari','Jasmin Noir','Hunter, Armaf'),
('Bvlgari','Falkar','Vigour, Zimaya Cosmopolitan Dubai, Paris Corner'),
('Byredo','Black Saffron','Accord Homme, Riiffs By Saffron, Maison Alhambra Black Symphony, Zimaya Vibrant Sensual Saffron, Emir'),
('Byredo','Tobacco Mandarin','Vibrant Spicy Tobacco, Emir Athoor Al Alam Khulood Gold, Fragrance World Tobacco D Feu, French Avenue, Fragrance World'),
('Byredo','Bal D afrique','Al Rayhan, Attar Collection Vibrant Vetiver Delight, Paris Corner'),
('Byredo','Rose of No Man s Land','Roses are White, Zimaya Athoor Al Alam, Rawah, Fragrance World Roses D Emotion, French Avenue, Fragrance World'),
('Byredo','Biblioteque','Berlinetta, Maison Alhambra'),
('Byredo','Sundazed','Awaan, Lattafa Pride'),
('Cacharel','Amor Amor Love Festival','Amore, Dubai Essences'),
('Calvin Klein','Euphoria','Euzonea, Maison Alhambra Emporia, Fragrance World Ethereal Femme, Paris Corner'),
('Calvin Klein','Liquid Gold Euphoria','Tag-Her Prestige, Armaf'),
('Carolina Herrara','CH Men Prive Discountinued','Oudh Burma, Al Haramain'),
('Carolina Herrara','Mystery Tobacco','Charuto Mysterious Tobacco, Paris Corner Exclusif Tabac, Maison Alhambra Tobacco Myth, Fragrance World'),
('Carolina Herrara','Good Girl','Bit Hooran, Ard Al Zaafaran B.A.D Femme, Maison Alhambra Qimmah for Women, Lattafa Ishraq Gold, Orientica Shaghaf Pour Femme, RASASI Rawaa, Al Haramain Classy Chic Girl, Fragrance World Pride of Armaf Women, Armaf Z38, Zakat'),
('Carolina Herrara','Good Girl Blush','Le Style Blush, Zakat'),
('Carolina Herrara','Saffron Lazuli','Exclusif Saffron, Maison Alhambra Lapis Lazuli, Fragrance World'),
('Carolina Herrara','Burning Rose','Exclusif Rose, Maison Alhambra'),
('Carolina Herrara','Oud Couture','Exclusif Oud, Maison Alhambra'),
('Brittany Spears','Fantasy','Feast, Dubai Essences'),
('Carolina Herrara','Bad Boy','B.A.D. Homme, Maison Alhambra Bad Lad le Parfum, Fragrance World'),
('Carolina Herrara','Scandal Ruby','Jasper Rouge, Fragrance World'),
('Carolina Herrera','CH Men Sport','Surf, Armaf'),
('Carolina Herrera','Cobalt Blue','Pacific Woods, Granduer Elite'),
('Carolina Herrera','212','No. 2 Men, Maison Alhambra'),
('Carolina Herrera','212 VIP Rose','Rose Seduction VIP, Maison Alhambra'),
('Carolina Herrera','212 Sexy','Deux Cent Douze, Fragrance World'),
('Carolina Herrera','212 VIP Black','Deux Cent Douze VIP Black, Fragrance World'),
('Carolina Herrera','212 Heroes','507 Premier, Dubai Essences'),
('Carolina Herrera','Gold Myrrh Absolute','Absolute Gold, Fragrance World'),
('Cartier','Declaration','Caliber Declaration, Fragrance World'),
('Chanel','Bleu De Chanel','Club De Nuit Iconic, Armaf Amber Oud Bleu Edition, Al Haramain Blue de Chance, Maison Alhambra Tag-Him, Armaf Maitre de Blue, Maison Alhambra The Blue, Paris Corner Voyage Bleu, Armaf Shades Blue, Armaf'),
('Chanel','Coco Mademoiselle','Como Moiselle, Maison Alhambra Rain Drops, Ajmal Club De Nuit Women, Armaf Como Moiselle, Maison Alhambra Z2, Zakat'),
('Chanel','Platinum Egoiste','Men s Legesi Pour Homme, Armaf'),
('Chanel','Sycomore','Lalique, Encre Noir Extreme (NOT ARABIC)'),
('Chanel','Allure Homme Sport','Alpine Homme Sport, Maison Alhambra'),
('Chanel','Allure Homme Sport Extreme','Da La Marque Brune, Armaf'),
('Chanel','Chance Eau Tendre','Chants Tenderina, Maison Alhambra La Muse Chance, Lattafa'),
('Chanel','Chance','Chance, Fragrance World'),
('Chanel','Allure','Inara, Swiss Arabian'),
('Chanel','Bleu De Chanel EDT','Amber Oud Bleu Edition, Al Haramain'),
('Chanel','Coco Mademoiselle EDT','Sotoor WAAW, RASASI Amber Oud White, Al Haramain'),
('Chloe','Chloe Eau de Parfum','Shiyaaka White EDP, Khadlaj'),
('Chopard','Oud Malaki','Sotoor WAAW, RASASI'),
('Chopard','Love','Enigma Quatre, French Avenue, Fragrance World'),
('Chopard','Happy Spirit','High Street, Armaf'),
('Clinique','Aromatics in White','iDiva Noir, Armaf'),
('Clive Christian','C Men','Eternia, Armaf Evoke Black, Armaf'),
('Coach','Dreams Sunset','Sunset Rose, Maison Alhambra'),
('Creed','Royal Oud','Rose Oud, Al Haramain Highness Green, Afnan Oud Royal, Fragrance World Ministry of Oud'),
('Creed','Queen of Silk','Kianna Crush, Afnan'),
('Creed','Erolfa','Amber Oud Exclusif Emerald, Al Haramain'),
('Creed','Spring Flowers','Anhaar Valley, Zimaya (?)'),
('Creed','Original Santal','Shades, Armaf'),
('Creed','Aventus','L aventure, Al Haramain Club De Nuit Intense, LTD Edition, Armaf Hypnotic Amber Spiritus, Borouj Avant, Maison Alhambra The Official Club Intense, Maison Alhambra Shaheen Silver, Lattafa Al Dur Al Maknoon Silver, Lattafa Sharaf the Club, Zimaya Ombre Extreme 05, Fragrance World Best, Orientica Rumz Al Rasasi 9325 Pour Lui, RASASI L aventure Intense, Al Haramain Infini, Khadlaj Hypnotic Amber, Arabiyat Prestige Emporer 2, Fragrance World Opulentia Primus Men, Emir Nuit, Fragrance World Imperia, Rayhaan Tres Bon, Armaf iDivo, Armaf'),
('Creed','Absolu Aventus','Club de Nuit Precieux, Armaf Hawas Black, Rasasi'),
('Creed','Aventus for Her','L aventure Fem, Al Haramain'),
('Creed','Millesime Imperial','Club De Nuit Milestone, Armaf Imperial Gold, Orientica Opulentia Empyreal, Emir'),
('Creed','Green Irish Tweed','Raghba for Men, Lattafa Tres Nuit, Armaf Egra Men, RASASI Amber Oud Carbon, Al Haramain L aventure Knight, Al Haramain Ash aa Oud Noir,  Arabiyat Prestige Aventos Green, Fragrance World'),
('Creed','Centaurus','Crimson, Ryhaan'),
('Creed','Silver Mountain Water','Maharjan Silver, Lattafa Mumayaz, Orientica Al Wisam Day, RASASI Supremacy in Heaven, Afnan CDN Sillage Creed, Armaf L Aventure Blanche, Al Haramain Opulentia Inverno, Emir Brown Orchid Blanc, Fragrance World Derby Club House Blanche, Armaf'),
('Davidoff','Cool Water','Waterfall, Orientica'),
('Del Pozo','Halloween','Holiday, Dubai Essences'),
('Dior','Oud Rosewood','Rose Oud, Maison Alhambra'),
('Dior','Tobacolor','TABAC, Maison Alhambra Tobacco Honey, Rogue Perfumes'),
('Dior','Purple Oud','Purple Wood, Maison Alhambra'),
('Dior','Ambre Nuit','Amber Night Privezarah, Paris Corner'),
('Dior','Leather Oud','L oudh, Maison Alhambra Leather Oud, Fragrance World'),
('Dior','Gris Dior','Grise, Maison Alhambra'),
('Dior','Gris Montaigne','Grey Mountain Privezarah, Paris Corner'),
('Dior','Homme Intense','Riiffs Elegant Homme Camaro Homme Intense D antiquities 1886, Lattafa Pride (twist) Truly for Men, RASASI Dark Door Intense, Maison Alhambra La Collection D Antiquites 1886, Lataffa Futura La Homme, Armaf'),
('Dior','Sauvage','Club De Nuit Urban Man Elixir, Armaf Salvo, Maison Alhambra Ventana Pour Homme, Armaf Khafaya, Zimaya Rumz Al Rasasi 9459 Pour Lui, RASASI The Pride of Armaf, Armaf Superior Privezarah, Paris Corner Elegido, Dubai Essences Zukhruf Black, Zimaya'),
('Dior','Sauvage Very Cool Spray','Magnificent Blue Pour Homme, Armaf'),
('Dior','Sauvage Elixir','Asad, Lattafa Azlan Oud Bleu Edition, Haramain Enigma Une, Fragrance World Salvo Elixir, Maison Alhambra'),
('Dior','Homme Original','Futura La Homme, Armaf'),
('Dior','Homme 2020','Desert Star, Armaf'),
('Dior','Sauvage Eau de Parfum','I Am The King, Ard Al Zaafaran'),
('Dior','Sauvage EDT','Modest Une, Afnan Hunter Intense, Armaf'),
('Dior','Feve Deliciouse','Frenetic Delicieuse, Paris Corner'),
('Dior','Fahrenheit','Fortnight for Men, Maison Alhambra Bois Luxura, Armaf Renheit Parfum, Fragrance World'),
('Dior','Fahrenheit Summer','Bois Luxura, Armaf'),
('Dior','Poison Girl','Fusion Girl, Maison Alhambra Yara, Lattafa Eternia, Armaf Z39, Zakat'),
('Dior','Purple Oud','Purple Wood, Maison Alhambra'),
('Dior','Leather Oud','L oudh, Maison Alhambra'),
('Dior','Gris Dior','Grise, Maison Alhambra'),
('Dior','Bois d Argent','Bois Dores Privezarah, Paris Corner'),
('Dior','J adore','Jardin de Paris, Maison Alhambra L aventure Gold, Al Haramain Ador, Fragrance World'),
('Dior','Pure Poison','Pure Instinct, Paris Corner Pendora'),
('Dior','Sauvage Intense','Salvo Intense, Maison Alhambra'),
('Dior','Forever and Ever','Athoor Al Alam, Secret Musk, Fragrance World'),
('Dior','Oud Rosewood','Rose Oud, Maison Alhambra'),
('Dior','Oud Ispahan','L Oudh, Maison Alhambra Oud Highness Privezarah, Paris Corner'),
('Dior','Miss Dior','Dear Cherry, Fragrance World Miss Dona Rossa, Paris Corner'),
('Dior','Addict','Adicto Noir, Fragrance World'),
('Dolce & Gabbana','Velvet Tender Oud','Shaghaf Oud, Swiss Arabian '),
('Dolce & Gabbana','Light Blue Forever','Feroce Pour Homme, Fragrance World'),
('Dolce & Gabbana','Light Blue Womens','Tag-Her, Armaf Vanity Femme Essence, Armaf'),
('Dolce & Gabbana','Pour Femme Intense','Italiano Donna, Armaf'),
('Dolce & Gabbana','Pour Homme Intenso','Suspenso, Fragrance World'),
('Dolce & Gabbana','K','Kingsman, Maison Alhambra Ra ed Luxe, Lattafa Riche & Royal, Fragrance World'),
('Dolce & Gabbana','K Eau de Parfum','Riche & Royal Intense, Fragrance World'),
('Dolce & Gabbana','The One Luminous Night','Lumiere Garcon, Fragrance World'),
('Dolce & Gabbana','The One Intense','Champ De Rose, Fragrance World'),
('Dolce & Gabbana','The One Exclusive Edition','Nuit Royale Exclusive Edition, Maison Alhambra'),
('Dolce & Gabbana','The One','Qasaed Al Sultan, Lattafa Pendora Scents Dream Catcher, Paris Corner'),
('Dolce & Gabbana','The One for Men Eau de Parfum','La Uno El Uno Para Hombres, Fragrance World'),
('Dolce & Gabbana','Light Blue EDT','24K White Gold, Lattafa'),
('Dolce & Gabbana','Velvet Desert Oud','Qaa ed, Lattafa'),
('Dolce & Gabbana','L Imperatrice 3','L Impressio III, Maison Alhambra'),
('Dolce & Gabbana','Anthology L Imperatrice 3','3 Impressions, Paris Corner'),
('Donna Karan','DKNY Be Delicious Green','NY Green, Dubai Essences'),
('Dreis Van Noten','Soie Malaquais','Peace and Love, Lattafa'),
('Elie Saab','Le Parfum Royal','Emaan, Lattafa Eminent Royal, Maison Alhambra Mazaaji, Lattafa'),
('Emporo Armani','Because It s You','Your Touch for Women, Maison Alhambra'),
('Escada','Especially Escada','Pear Potion, Emir'),
('Escentric Molecules','Molecule 02','Monocline 02, Maison Alhambra Esscentric 02, Fragrance World'),
('Escentric Molecules','Molecule 01','Montaigne Vanille, Maison Alhambra Esscentric 01, Fragrance World'),
('Escentric Molecules','Molecule 05','Monocline 05, Maison Alhambra Esscentric 06, Fragrance World'),
('Estee Lauder','Modern Muse','Le Parfait Pour Femme, Armaf'),
('Ex Nihilo','Fleur Narcotique','Azora, Attar Collection Reflect, Zimaya, Afnan Fluer De Orientica, Orientica La Fleur Bouquet, Afnan Narcotic Flower, Maison Alhambra Reflect, Zimaya Le Fleur Narcotique, Fragrance World'),
('Ex Nihilo','Blue Talisman','Taj 2, Fragrance World'),
('Fendi','Life Essence','Friend, Fragrance World'),
('Fenty','Fenty','Monarch Al Wataniah, Rawae e December Rose, Paris Corner'),
('Ferragamo','Intense Leather','Infinite Pour Homme, Fragrance World'),
('Fragrance Du Bois','Cannabis Blue','Posh Mirage, Fragrance World'),
('Fragrance One','Office For Men','Ejazzi Regular, Lattafa'),
('Franck Boclet','Cocaine','Wayward Charlie, Paris Corner'),
('Franck Boclet','Sugar','Forbidden Sugar, Paris Corner'),
('Frederic Malle','The Night','The Artist No. 2, Maison Alhambra The Night, French Avenue, Fragrance World'),
('Frederic Malle','The Moon','Identify Oud Crescent, Emir'),
('Frederic Malle','Portrait of a Lady','Portrait d Une Dame, Aroma West The Artist No. 1, Maison Alhambra The Artist No. 2, Maison Alhambra Portfolio Floral Sculpture, Al Haramain Her Portrait, Rogue Perfumes French Portrait, Fragrance World Identity Unique Portrait, Paris Corner'),
('Giardini Di Toscana','Bianco Latte','Taskeen Caramel Cascade, Paris Corner Eclaire, Lattafa Tiramisu Caramel, Zimaya Nyla Vani-elle, Arabiyat Prestige'),
('Giorgio Armani','Acqua Di Gio (MEN)','Jorge Di Profumo, Maison Alhambra Clasico de Intense, Paris Corner Blue Homme, Armaf'),
('Giorgio Armani','Stronger with You','Your Touch, Maison Alhambra'),
('Giorgio Armani','Stronger With You Absolutely','Proud of You Absolute, Fragrance World'),
('Giorgio Armani','Stronger With You Oud','Veteran Oud, Paris Corner'),
('Giorgio Armani','Rouge Malachite','Afaq, Lattafa '),
('Giorgio Armani','Rose D arabie','Velvet Rose, Lattafa Private Army Rose Arabia, Fragrance World'),
('Giorgio Armani','Oud Royal','Opulent Oud, Lattafa'),
('Giorgio Armani','Acqua Di Gioia (Women)','Mayar Natural Intense, Lattafa (twist)'),
('Giorgio Armani','Acqua Di Gio Profumo','Suqraat, Lattafa'),
('Giorgio Armani','Acqua Di Gio Absolu','Hawas, Rasasi'),
('Giorgio Armani','Acqua Di Gio Profondo','Liam Blue Shine, Lattafa Jorge di Profondo, Maison Alhambra Tres Nuit Lyric, Armaf'),
('Gisada','Ambassador Intense','Oros Pure Affecte, Armaf'),
('Gissah','Imperial Valley','Imperial, Fragrance World Khair, Paris Corner Uhibuk Akthar Rijali, Fragrance World'),
('Gissah','The Jewel','Jewel of Kuwait, Rouge Perfumes'),
('Gissah','Sava','Royal Blend Nero, French Avenue, Fragrance World'),
('Givenchy','Gentleman Reserve Privee','Reserve Privee, Albait Aldimashqi Qaa ed Intense, Lattafa Genuine Man Giovany Reserve, Fragrance World'),
('Givenchy','Gentlemen Only','Vitesse, Armaf'),
('Givenchy','Gelteman','Sincerity, Grandeur'),
('Givenchy','L interdit Eau de Parfum','L intrude, Maison Alhambra Fakhar Rose, Lattafa  Prohibit Intense, Fragrance World'),
('Givenchy','L interdit Eau de Parfum Intense','Prohibit Parfum Intense, Fragrance World'),
('Givenchy','L interdit Eau de Parfum Rouge','Prohibit Rouge, Fragrance World'),
('Givenchy','Eaudemoiselle de Givenchy','EauDeMadame De Giovany, Fragrance World'),
('Givenchy','Eaudemoiselle de Givenchy Ambre Velours','EauDeMadame Velvet Amber, Fragrance World'),
('Givenchy','Eaudemoiselle Essence des Palais','EauDeMadame De Femme BlackNRose, Fragrance World'),
('Givenchy','Live Irresistible ','Sauville Pour Femme, Armaf'),
('Goldfield & Banks','Silky Woods','Casablanca, Swiss Arabian Qasamat Ebhar, RASASI'),
('Gucci','A Chant for the Nymph','The Chant, Maison Alhambra'),
('Gucci','Intense Oud','Intense Oud, Paris Corner'),
('Gucci','Flora','Florence, Maison Alhambra Flawsome, Paris Corner'),
('Gucci','A Gloaming Night','An Evening Twilight, Fragrance World'),
('Gucci','The Voice of the Snake','The Serpent, Maison Alhambra The Haunting Blend, Fragrance World'),
('Gucci','Bloom','Floral Bloom, Maison Alhambra Floriana, Rayhaan'),
('Gucci','Bloom Ambrosia di Fiori','Floral Ambrosia, Maison Alhambra'),
('Gucci','Flora Gorgeous Gardenia','Haya, Lattafa Mazharia, Zimaya'),
('Gucci','Guilty Pour Homme','Sotoor TAA , RASASI His Dynasty, MPF'),
('Gucci','Guilty for Women','Her Dynasty, MPF'),
('Gucci','Gucci Eau de Parfum','Sotoor SEEN, RASASI'),
('Gucci','A Midnight Stroll','The Trail, Maison Alhambra'),
('Gucci','A Song for the Rose','The Myth, Maison Alhambra'),
('Gucci','Bloom Profumo di Fiori','Floral Profumo, Maison Alhambra'),
('Guerlain','Spiritueuse Double Vanille','Vanilla So Sweet, Fragrance World'),
('Guerlain','Santal Royal','Sehr Al Sheila, Swiss Arabian'),
('Guerlain','Oud Essential','Qaa ed Al Shabaab, Lattafa'),
('Guerlain','L Homme Ideal Extreme','L Homme Extreme, Fragrance World Supreme L Homme Extreme, Fragrance World'),
('Guerlain','La Petite Robe Noire Rose','Queen of Hearts, Fragrance World My Black Dress, Paris Corner'),
('Guerlain','Patchouli Ardent','Amberly Ombre Blue, Maison Alhambra'),
('Guerlain','Herbes Troublantes','Fresh as Citrus, Fragrance World'),
('Guerlain','Musc Noble','Amberly Amoroso, Maison Alhambra'),
('Guerlain','Cuir Beluga','Leather so Rare, Fragrance World'),
('Guerlain','Cuir Intense','Singatures No 1, Maison Alhambra Cosmopolitan London, Paris Corner'),
('Guerlain','Cherry Oud','Ambroise, Fragrance World Afrah Cherry, Mamlakat Al Oud'),
('Guerlain','Joyeuse Tubereuse','White as Tuberose, Fragrance World'),
('Guerlain','Epices Volees','Pepper so Spicy, Fragrance World'),
('Guerlain','Bois d Armenie','Dark as Wood, Fragrance World'),
('Guerlain','Rose Cherie','Pose as Rose, Fragrance World'),
('Guy Laroche','Drakkar Noir','Drive Now, Dubai Essences'),
('Halloween','Halloween','Hallo Queen, Fragrance World'),
('Hermes','Twilly','Tweet, Maison Alhambra'),
('Hermes','Terre d Hermes','Fattan, Rasasi Toro Pour Homme, Maison Alhambra Tour de Havana, Fragrance World Derby Club House Belmont, Armaf'),
('Hermes','Terre d Hermes Eau Intense Vetiver','Paradox Vetiver, French Avenue, Fragrance World'),
('Hugo Boss','Boss Bottled Intense','Pinnace Noir, French Ave, Fragrance World Athoor Al Alam, Nazih Silver, Fragrance World'),
('Hugo Boss','Boss Orange','Bronze for Man, Maison Alhambra'),
('Hugo Boss','Hugo','Commander for Men, Dubai Essences'),
('Initio','Paragon','Vintage Radio, Lataffa'),
('Initio','Musk Therapy','Infini Musk, Maison Alhambra Glorious Oud Royal Blanc, Fragrance World Musk is Great, Zimaya Pure Musk, Afnan (twist) La Fede Oud for Glory, Khadlaj Ivory Musk, Fragrance World'),
('Initio','Oud for Happiness','Infini Oud Joyous, Maison Alhambra Al Noble Safeer, Lattafa Happy Oud, Zimaya Art of Wood, Lattafa Intro Joyness Oud, Fragrance World Happiness Oud, French Avenue, Fragrance World'),
('Initio','Oud for Greatness','Badee Al Oud Oud for Glory, Lattafa Supremacy in Oud, Afnan Shaghaf Oud Royal, Swiss Arabian Oud is Great, Zimaya La Fede Oud for Kings*, Khadlaj (I THINK) Glorious Oud, French Avenue, Fragrance World Royale Black, Zakat Supreme Oud, Dubai Essences'),
('Initio','Atomic Rose','Infini Rose, Maison Alhambra Badee Al Oud Amethyst, Lataffa Athoor Al Alam Al Zahra Aswad, Fragrance World Royale Amethyst, Zakat'),
('Initio','Narcotic Delight','Nudo Exotic Flowers, Fragrance World Ka Fede Oud for Victory, Khadlaj'),
('Initio','Side Effect','After Effect, French Avenue, Fragrance World Intro Aftermath, Paris Corner'),
('Initio','Addictive Vibration','Intense Addiction, French Avenue'),
('Issey Miyake','L Eau D Issey Pour Homme Noir Ambre','Majdal Sultan, ASDAAF Deep Amber, Rogue Perfumes'),
('Issey Miyake','Nuit D Issey Polaris','Qaa ed, Lattafa'),
('Jacomo','Jacomo for Her','Niche Purple Amethyst, Armaf'),
('Jean Paul Gaultier','Ultra Male','Ramz Silver, Lattafa 9pm, Afnan Glacier Ultra, Maison Alhambra'),
('Jean Paul Gaultier','Scandal','Odyssey Mandarin Sky, Armaf So Candid, Maison Alhambra Prima Donna, MPF Belle Celine Scandant, Fragrance World'),
('Jean Paul Gaultier','Scandal By Night','Belle Celine Scandant By Night, Fragrance World'),
('Jean Paul Gaultier','Scandal for Him','Gossip, MPF'),
('Jean Paul Gaultier','Le Beau','Kaheela Platinum, Paris Corner Glacier Bold, Maison Alhambra'),
('Jean Paul Gaultier','Le Male','Glacial Le Noir, Maison Alhambra Essecia La Homme Le Parfum, Fragrance World Glacier Pour Homme, Maison Alhambra The Kingdom for Men, Lattafa'),
('Jean Paul Gaultier','La Belle','Glacier Bella, Maison Alhambra Casablanca, Swiss Arabian Teriaq, Lattafa'),
('Jean Paul Gaultier','La Belle Le Parfum','Hayaati Belle, Fragrance World'),
('Jean Paul Gaultier','So Scandal','Amal, Ard Al Zaafaran Belle Celine Scandant So Nice!, Fragrance World'),
('Jean Paul Gaultier','Divine','Hypnotic Vanilla, Arabiyat Prestige'),
('Jean Paul Gaultier','Classique','L femme Classic, Dubai Essences'),
('Jimmy Choo','I Want Choo','Voyage Hawaii Pour Femme, Armaf'),
('Jo Malone','Scarlet Poppy Intense','Athoor Al Alam Ishqat Al Lail, Fragrance World'),
('Jo Malone','Wood Sage & Sea Salt','Salty Breeze, Autobiography'),
('Jo Malone','Ginger Biscuit','Ginger Babe, Aroma Concepts'),
('Kayali','Silk Santal','Khair Felicity, Paris Corner '),
('Kayali','Yum Boujee Marshmellow','Marshmellow Blush, Paris Corner Cloud Candy, Khadlaj'),
('Kayali','Yum Pistachio','Affection, Lattafa Pride Khair Pistachio, Paris Corner Forever Blue, Ard Al Zaafaran Lucious, Fragrance World Kianna Angel, Afnan'),
('Kayali','Eden Juicy Apple','Badee Al Oud Sublime, Lattafa La Fede Aura Kiss of Rose, Khadlaj Belle Dolce Red Delice, Fragrance World'),
('Kayali','Vanilla 28','Choco Musk, Al Rehab (?) Spanish Vanilla, Al Rehab (?)'),
('Kayali','Eden Sparkling Lychee','Khair Fusion, Paris Corner'),
('Kayali','Vanilla Royale Sugared Patchouli','December Vanilla, Paris Corner'),
('Kayali','Vanilla Candy Rock Sugar','Khair Confection, Paris Corner Juicy Melange, Paris Corner'),
('Kayali','Lovefest Burning Cherry','Ophidian Black Cherry, Paris Corner Deep Love, Rogue Perfumes'),
('Kenneth Cole','Black','Craze Noir, Armaf'),
('Kenzo','Flower','Aromatic Rouge, Maison Alhambra'),
('Khadlaj','Hareem al Sultan Silver','Roaa al Sharq Silver, Khadlaj'),
('Khadlaj','Hareem al Sultan Gold','Roaa al Sharq Gold, Khadlaj Sultan Golden Crown, Rogue Perfumes'),
('Kilian','Love, Don t Be Shy','Ciao Pour Femme, Riffs Ansaam Gold, Lattafa'),
('Kilian','Good Girl Gone Bad','Kismet for Women, Maison Alhambra A La Rose, Zimaya'),
('Kilian','Angels Share','Kismet Angel, Maison Alhambra Khamrah, Lattafa Fire Your Desire, Emir Cocktail Intense, Fragrance World Sharaf Blend, Zimaya La Fede Intoxicate, Khadlaj Aariz Intense, Arabiyt Prestige Cognac Blaze, Mawj (Paris Corner) Royal Blend, French Avenue, Fragrance World Enigma Deux, French Avenue, Fragrance World Riqqa, Ard Al Zaafaran  Royale Opal, Zakat'),
('Kilian','Straight to Heaven','A Fairy Tale, Zimaya White Heaven, Rogue Perfumes'),
('Kilian','Black Phantom','Spectre Wraith, Fragrance World Abyssal Allure, Rogue Perfumes'),
('Kilian','Blue Moon Ginger Dash','Moscow Mule, Mawj (Paris Corner) Dashed Moon, Rogue Perfumes'),
('Kilian','Apple Brandy on the Rocks','Appletini, Mawj, Paris Corner Apple Pie, Rogue Perfumes'),
('Kilian','Vodka on the Rocks','Kismet Moscow, Maison Alhambra'),
('Kilian','Intoxicated','Intoxicated, Rogue Perfumes'),
('Kilian','Dark Lord','Black Ghost, Rogue Perfumes'),
('Kilian','Rose Oud','Shades Wood, Armaf'),
('La Perla','Divina Silver Edition','iDiva, Armaf'),
('Lacoste','Blanc','Hunter, Armaf'),
('Lacoste','L. 12. 12. White','Hunter Man, Armaf'),
('Lacoste','Lacoste Pour Femme','Coastal Pour Femme, Maison Alhambra'),
('Lalique','Encre Noire','Anchor Black, Maison Alhambra Black Ink, Fragrance World'),
('Lalique','L Amour','Amour de Leuxe, Fragrance World'),
('Lancome','Oud Bouquet','Shaghaf Oud, Swiss Arabian  Oud Mood, Lattafa Sheikh Al Shuyukh Luxe Edition, Lattafa Noor Oud, Zimaya Oud Saffron, Orientica Manege Blanche, Al Haramain Brown Orchid Oud, Fragrance World'),
('Lancome','La vie Ese Belle','Ted Lapidus, Orissima La Vita Bella, Maison Alhambra Fannan Wardi, Orientica Hawas for Her, RASASI La Vida es Bella, Fragrance World Z17, Zakat La Vida De Vivi Fleur, Dubai Essences'),
('Lancome','La Nuit Tresor','La Nuit Pendora, Paris Corner La Nuit Rose, Fragrance World Signature True, Armaf Modest Deux Femme, Afnan'),
('Lancome','La Vie Est Belle Intense','La Vita Bella Intensa, Maison Alhambra'),
('Lancome','Idole','Pride, Maison Alhambra Glossy, Maison Alhambra'),
('Lancome','L idole L intense','Ekhtiari, Lattafa'),
('Lancome','Hypnose','Daarej Pour Femme, RASASI'),
('Lancome','Tresor Midnight Rose','La Fede Bella Reve Dolce Fior, Khadlaj'),
('Lanvin','Eclat D arpege','Aura D eclat, Maison Alhambra Arpege la Violette, Fragrance World Eclectic D Femme, Paris Corner Tres Jour, Armaf'),
('Lanvin','Marry Me','Just Married, Maison Alhambra'),
('Lanvin','Jeanne Lanvin Couture','Italiano Vivo, Armaf'),
('Lattafa','Yara','Just (pink), Fragrance World'),
('Le Labo','Santal 33','Amber Noir, Orientica Emir Rich Santal, Paris Corner King Asad, Zakat'),
('Le Labo','Bergamot 22','Magnate Premiere, Khadlaj  Just Burgamot Emir Factory Edition, Paris Corner'),
('Le Labo','Another 13','Soothing Zephyr, Paris Corner'),
('Les Liquides Imaginaires','Blanche Bete','Her Confession, Lattafa Taskeen Lactea Divina, Paris Corner'),
('Lorenzo Villoresi','Teint de Neige','Janoon, Al Haramain Athoor Al Alam Muski, Fragrance World'),
('Louis Vitton','Spell on You','Chant on You, Luxe Vision'),
('Louis Vuitton','Ombre Nomade','Leather Gold, Oros Pure Wild Night Shadow, Zimaya Ilham Al Oud, Zimaya Al Qiam Gold, Lattafa The Shadow, French Avenue (Fragrance World) Jacques Yves Soleil D Ombre, Fragrance World Ombre Nimbus, Lucianno (Lattafa) Ombre de Louis Privezarah, Paris Corner'),
('Louis Vuitton','Pacific Chill','Pinnace, Fragrance World Coastal Breeze, Lucianno (Lattafa) Bateig Azul, Afnan'),
('Louis Vuitton','Nuit de Feu','The Fire, FA Paris'),
('Louis Vuitton','California Dream','California Vibe, Lucianno (Lattafa)'),
('Louis Vuitton','Stellar Times','Musamam White Intense, Lattafa Hayam, Zimaya Lumiere Elle, French Avenue, Fragrance World'),
('Louis Vuitton','L immensite','Jean Lowe Immortal, Maison Alhambra Magnitutde, Lucianno (Lattafa)'),
('Louis Vuitton','Matiere Noire','Jean Lowe Matiere, Maison Alhambra Essence De Noir, Fragrance World'),
('Louis Vuitton','Imagination','Saheb Intense, Ard Al Zaafaran Fascination, Luxe Vision Amber Oud Aqua Dubai, Al Haramain TROIS III, North Stag Expressions Mystic Dream, Lucianno (Lattafa)'),
('Louis Vuitton','Rose des Vents','Rose of Dreams, Zimaya'),
('Louis Vuitton','Nouveau Monde','Jean Lowe Nouveau, Maison Alhambra'),
('Louis Vuitton','City of Stars','Stars City, Ether Perfumes Shining City, Milestone Golden Hour, Volare'),
('Louis Vuitton','Afternoon Swim','Soaked Sun Exclusif, Grandeur Elite Quatre IV, North Stag Expressions Sunset Swim, Lucianno (Lattafa)'),
('Louis Vuitton','On the Beach','By the Seashore, Luxe Vision'),
('Louis Vuitton','Pur Oud','Pur Oud, Maison Alhambra'),
('Maison Crivelli','Hibiscus Mahajad','Artisan Perfumo Hibiscus Magic, Fragrance World Le Prestige Royal, Khadlaj Tea + More, Rogue Perfumes'),
('Maison Crivelli','Oud Maracuja','Ajwad Pink to Pink, Lattafa Azzure Aoud, French Avenue (Fragrance World)'),
('Maison Francis Kurkdjian','Baccarat Rouge 540','Pure Addiction, Franck Olivier Manege Rouge, Al Haramain Amber Oud Exclusif: Bleu, Al Haramain Club De Nuit Untold, Armaf Ana Abiyedh Rouge, Lattafa Baroque Rouge 540, Maison Alhambra Bouquet Red, Zimaya Xclusif Oud Rouge, Orientica Qasamat Bareeq, RASASI Barakkat Rouge 540, Fragrance World Philos Rosso, Maison Alhambra B Rouge, Fragrance World Z26, Zakat'),
('Maison Francis Kurkdjian','Baccarat Rouge 540 Extrait','Amber Oud Ruby Edition, Haramain Aura, Lattafa Baroque, Maison Alhambra Oniro Rouge, Fragrance World Le Prestige Bold, Khadlaj Z96, Zakat'),
('Maison Francis Kurkdjian','Oud Satin Mood','Baroque Satin Oud, Maison Alhambra Oud Satin, Ministry of Oud, Paris Corner L xtase Rose Absolue, Nina Ricci (NOT ARABIC) Impulse Oud, Zimaya Barakkat Satin Oud, Fragrance World'),
('Maison Francis Kurkdjian','Gentle Fluidity Gold','Velvet Gold, Orientica Barakkat Gentle Gold, Fragrance World'),
('Maison Francis Kurkdjian','Gentle Fluidity Silver','Varakh Silver, Fragrance World'),
('Maison Francis Kurkdjian','Gentle Aquae Vitae','Barakkat Aqua Aevum, Fragrance World'),
('Maison Francis Kurkdjian','Grand Soir','Eternal Oud, Lattafa Soir, Fragrance World Barakkat Ambre Eve, Fragrance World'),
('Maison Francis Kurkdjian','Aqua Celestia','Barakkat Aqua Stellar, Fragrance World'),
('Maison Martin Margiela','By The Fireplace','Hypnotic Oud Camp Fire, Emir Factory Edition Ameer Al Oudh Intense, Lattafa Olfactory Bonfire, Fragrance World Ace of Spades, Fragrance World'),
('Maison Martin Margiela','Jazz Club','Olfactory Music Fest, Fragrance World'),
('Maison Martin Margiela','On a Date','Date Night, Maison Asrar'),
('Mancera','Tonka Cola','Cherry Cola, Emir (Paris Corner)'),
('Mancera','Amore Caffè ','Coffee Latte, Khadlaj Tiramisu Coco, Zimaya'),
('Mancera','Instant Crush','Manege Blanche, Al Haramain Celestia Viola, Fragrance World Afkaar, Lattafa Athoor Al Alam Al Sayaad for Women, Fragrance World'),
('Mancera','Red Tobacco','Perlador, Borouj Instant Tobacco, Maison Alhambra Tobacco Rouge, Paris Corner Hunter Killer, Armaf'),
('Mancera','Black Prestigium','Aoud Prestigium, Maison Alhambra'),
('Mancera','Cedrat Boise','Citrus Oud, Arabiyat Prestige'),
('Mancera','Roses Vanille','Lahdath, Lattafa Rose de Orientica, Orientica Qidwah, Ard Al Zaafaran'),
('Mancera','Coco Vanille','Montaigne Coco, Maison Alhambra'),
('Marc Jacobs','Perfect Intense','Yara Moi, Lattafa Precious Gold, Maison Alhambra'),
('Marc Jacobs','Perfect','Perfectly Pink, Grandeur Precious Pink, Maison Alhambra'),
('Marc-Antoine Barrois','Ganymede','Stallion, Zimaya Celestial, Emir, Paris Corner El Darodo Extrait, French Avenue (Fragrance World) '),
('Matiere Premiere','Vanilla Powder','Souvenir Blooming Bliss, Afnan Fursan White, Khadlaj'),
('Matiere Premiere','Encens Suave','Spicy Amber, French Avenue, Fragrance World'),
('Matiere Premiere','Crystal Saffron','Saffron Elixir, French Avenue, Fragrance World'),
('Matiere Premiere','Falcon Leather','Mystic Leather, French Avenue, Fragrance World'),
('Matiere Premiere','Radical Rose','Exotic Rose, French Avenue, Fragrance World'),
('Memo','Sintra','Melodie de Orientica, Orientica'),
('Memo','Irish Leather','Dublin Leather, Maison Alhambra Ana Abiyedh Leather, Lattafa Royal Leather, Zimaya La Yuqawam Ambergris Showers, RASASI Paradox Orient, French Avenue, Fragrance World Corium, Rayhaan'),
('Memo','Iberian Leather','Ghayath, Zimaya'),
('Memo','Magic','Grandeur, Zimaya'),
('Memo','African Leather','Herculean Leather, Maison Alhambra Afro Leather, Maison Alhambra'),
('Memo','Russian Leather','Russe Leather, Maison Alhambra'),
('Memo Paris','Italian Leather','Ana Abiyedh Leather, Lattafa Junoon Velvet Pour Homme, RASASI'),
('Michael Kors','Gold Rose Edition','Tres Altin, Armaf'),
('Molton Brown','Tobacco Absolute','Celestia Hazel, Fragrance World'),
('Mont Blanc','Explorer','Encode, Maison Alhambra'),
('Mont Blanc','Legend','Oniro Atom, Fragrance World Air Force, Dubai Essences'),
('Mont Blanc','Legend Spirit','Expose Blanc, Maison Alhambra'),
('Mont Blanc','Explorer Ultra Blue','Encode Blue, Maison Alhambra'),
('Montale','Intense Café','Tanasuk, Al Haramain Ajwad, Lataffa Café Intense, Monster Perfumes, Paris Corner Sara, Orientica'),
('Montale','Starry Nights','Valencia, Swiss Arabian'),
('Montale','Roses Musk','White Oud, Fayrouz Musk Vanille, Maison Alhambra L aventure Rose, Al Haramain'),
('Montale','Roses Night','Shams Al Shampoos Rose Taifi, Lattafa'),
('Montale','Arabians Tonka','Pendora Noir de Arabie, Fragrance World Taraf Black, Zimaya Karus Secret Musk, Khadlaj Noir D Arabie, Paris Corner Great Eagle of Arabia, Zakat'),
('Montale','Aoud Damascus','Oud Al Mubakhar, RASASI'),
('Montale','Mukhallat','Makkah, Al Haramain'),
('Montale','Aoud Musk','Athoor Al Alam Finest Oud, Fragrance World'),
('Montblanc','Legend Intense','Expose Intense, Maison Alhambra'),
('Montblanc','Emblem','Futura La Homme Intense, Armaf'),
('Moschino','I Love Love','Elite Woman Pink'),
('Mugler','Angels Ice Star','Ajayeb Dubai Portrait, Lattafa'),
('Mugler','Pure Malt','Star Men Nebula, Fragrance World Posh Malt, Fragrance Wolrd'),
('Mugler','Pure Havana','Insurrection II Wild, Reyane'),
('Mugler','Alien','Brown Orchid Amethyst, Fragrance World Sacrifice for Her, Ajmal'),
('Mugler','Alien Goddess','Pink Fame, Fragrance World'),
('Mugler','Angel Nova','Mayar, Lattafa Alive Now, Maison Alhambra'),
('Mugler','A*Men Pure Malt','Star Men Nebula, Fragrance World Eshq, Nusuk'),
('Mugler','Womanity','La Femme, Armaf'),
('Narciso Rodriguez','Poudree','Ana Abiyedh Poudree, Lattafa Narissa Poudree, Maison Alhambra Narceine Poudree, Paris Corner'),
('Narciso Rodriguez','Ambree','Narissa Ambre, Maison Alhambra Shahd, Lattafa Ombre, MPF'),
('Narciso Rodriguez','Rouge','Narissa Rouge, Maison Alhambra Brown Orchid Ruby, Fragrance World'),
('Narciso Rodriguez','For Her','Narissa For Her, Maison Alhambra Egra Women, RASASI Redriguez for Her Pink, Fragrance World'),
('Narciso Rodriguez','For Her Eau de Toilette (limited edition?)','Redriguez For Her Eau De Intense, Fragrance World'),
('Narciso Rodriguez','For Him','Redriguez Pour Homme, Fragrance World'),
('Narciso Rodriguez','Pure Musc','Redriguez For Her Prive Musc, Fragrance World'),
('Narotica','Narco Oasis','The Kingdom For Her, Lattafa'),
('Nasomatto','Black Afgano','Ameer Al Oudh, Lattafa Blend Afgano Privezarah, Paris Corner'),
('Navitus','Venom of Love','Mayar Cherry Intense, Lattafa (?)'),
('Nishane','Ani','Ard Al Zaafaran, Satwa Sceptre Ghost, Fragrance World Nasheet, Lattafa Satwa, Ard Al Zaafaran'),
('Nishane','Hacivat','Al Dana, Lattafa Niche Emarati 8th Wonder, Rogue Perfumes'),
('Nishane','Shem','Sultry Woods, French Avenue (Fragrance World)'),
('Nishane','Tero','Mazaaj, Zimaya'),
('Nishane','Fan Your Flames','Unspoken Pleasures, Rouge Perfumes'),
('Orto Parisi','Megamare','Megara, Maison Alhambra Atlas, Lattafa Stellar Oud, Khadlaj Aqua Pura, Fragrance World Megaron, Paris Corner Valar A Chaos in the Ocean, Emir'),
('Orto Parisi','Terroni','Terra, Maison Alhambra Maahir Black Edition, Lattafa'),
('Paco Rabanne','Invictus Victory','Victorioso, Maison Alhambra Wicked Noir, MPF Impactus, Dubai Essences'),
('Paco Rabanne','1 Million Lucky','Ishq Al Shuyukh Silver, Lattafa'),
('Paco Rabanne','1 Million Elixir','La Uno Million Elixir, Fragrance world'),
('Paco Rabanne','Invictus Aqua','Hawas Ice, Rasasi Arabian Sky, Armaf El Cielo Pour Homme, Armaf'),
('Paco Rabanne','Invictus Legend','Victorioso Legend, Maison Alhambra Wicked Legend, MPF'),
('Paco Rabanne','Invictus','Victorioso, Maison Alhambra Najdia, Lattafa Hayaati, Lattafa Oniro, Fragrance World Hawas, Rasasi Emporer 1, Fragrance World Wicked, MPF Pacific, Rayhaan Invicto, Fragrance World'),
('Paco Rabanne','Olympea','Olivia, Maison Alhambra'),
('Paco Rabanne','Black Xs','Qaed Al Fursan, Lattafa Italiano Nero, Armaf'),
('Paco Rabanne','One Million Golden Oud','Nazih Gold, Fragrance World'),
('Paco Rabanne','Invictus Elixir','Epoque Artistique, Khadlaj The Pride of Armaf Admiral Armaf, Armaf Wicked Elixir, MPF'),
('Paco Rabanne','Invictus Victory Elixir','TAG Uomo Rossa, Armaf'),
('Paco Rabanne','Fame','Yara Tous, Lattafa Gold Fame, Fragrance World Spirit Gold For Women, Dubai Essences'),
('Paco Rabanne','1 Million','Fakhar Gold Extrait, Lattafa Attar Al Mohabba Male, RASASI La Uno Million, Fragrance World Tag-Him Prestige, Armaf'),
('Paco Rabanne','Lady Million','Edition One, Armaf'),
('Paco Rabanne','Olympea Blossom','Olivia Blossom, Maison Alhambra'),
('Paco Rabanne','Phantom','Panther Pour Homme, Maison Alhambra'),
('Pana Dora','Swedish Wood','Al Noble Ameer, Lattafa'),
('Pana Dora','Velvet Iris','Al Noble Wazeer, Lattafa'),
('Parfums de Marly','Althair','Athan, Ainash Parfums Liquid Brun, Fragrance World Art of Nature II, Lattafa Pride'),
('Parfums de Marly','Delina A Rosee','Hawwa, Zimaya Taraf White, Zimaya'),
('Parfums de Marly','Valaya','Mystique Bouquet, Afan Bedour Extrait, Arabiyat Prestige'),
('Parfums de Marly','Layton','Black White, Lalique Detour Noir, Haramain Loyal Agar, Luxador Xclusif Oud Bleu, Orientica Premium Leyden, Maison Alhambra Royal Paragon, Zimaya Dusk The Woods, Fragrance World DEUX II, North Stag Expressions'),
('Parfums de Marly','Delina Exclusif','Club De Nuit Imperiale, Armaf Gravity, Borouj Lahdath, Lattafa'),
('Parfums de Marly','Pegasus','Portfolio Royale Stallion, Al Haramain Craze, Armaf Perseus, Maison Alhambra Phantom Paragon, Zimaya'),
('Parfums de Marly','Carlisle','Borouj, Perlador Tafakhar, Ard Al Zaafaran Cassius, Maison Alhambra'),
('Parfums de Marly','Greenley','Amber Oud Exclusif Emerald, Al Haramain Aether Extrait, French Avenue, Fragrance World Midori, Fragrance World'),
('Parfums de Marly','Oajan','Legion 1743, Fragrance World CinnaHoney, Rogue Perfumes'),
('Parfums de Marly','Delina','Romantic, Orientica Fatima Pink Extrait, Zimaya, Afnan Delilah, Maison Alhambra Rose 01, Swiss Arabian Rua, Paris Corner Thouq, Lattafa Hawwa Pink, Zimaya Arte Bellisimo Romantic, Orientica Elania, Emir Z12, Zakat Dakota, Grandeur Elite'),
('Parfums de Marly','Layton Exclusif','Black Diamond Incense, Ibraheem Al Qurashi Detour Noir Exclusif, Al Haramain Anaqeed, Fragrance World Miraj Absolu, French Avenue, Fragrance World'),
('Parfums de Marly','Althair','Aseel Special Edition, Arabian Oud Liquid Brun, Fragrance World Ghazala of Arabia, Zakat'),
('Parfums de Marly','Kalan','XO Sport, Orientica (red bottle) Kalos, Maison Alhambra Red Carpet Paragon, Zimaya'),
('Parfums de Marly','Sedley','Maahir Legacy, Lattafa'),
('Parfums de Marly','Oriana','Reyna, Maison Alhambra Ansaam Gold, Lattafa Nudo Sweet Berries, Fragrance World'),
('Parfums de Marly','Herod','Hercules, Maison Alhambra Majestic Empire, Rogue Perfumes Supreme Gold, Autobiography '),
('Parfums de Marly','Godolphin','Galatea, Maison Alhambra'),
('Parfums de Marly','Pegasus Exclusif','Detour Noir Intense, Al Haramain'),
('Parfums de Marly','Haltane','Detour Eco, Al Haramain Hartnell, Fragrance World Saffron Delight, Rogue Perfumes'),
('Parfums de Marly','Safanad','Fatima Velvet Love, Zimaya, Afnan'),
('Paris Hilton','Paris Hilton','Pink Party Pour, Dubai Essences'),
('Penhaligons','The Blazing Mr Sam','Apex, Fragrance World Blazing, Fragrance World'),
('Penhaligons','Halfeti Cedar','Mohra, Lattafa'),
('Penhaligons','The Bewitching Yasmine','Miraj Exclusif, Frenche Avenue, Paris Corner'),
('Penhaligons','The Tragedy of Lord George','Tragedy, Fragrance World Noble George Privezarah, Paris Corner'),
('Prada','L homme Prada','Avant Garde, Riiffs Evoke Gold for Him, Ajmal'),
('Prada','Luna Rossa','Pride Men Moon, Fragrance World'),
('Prada','Luna Rossa Ocean','Pride Marine Red Mood, Fragrance World'),
('Ralph Lauren','Polo Black','Skin Couture Classic Men, Armaf'),
('Reef','Reef 33','Taj 1, Fragrance World'),
('Revolution Makeup','Creative','Athoor Al Alam Ihtaj, Fragrance World'),
('Roja Dove','Amber Aoud','Divin Aoud, French Avenue, Fragrance World'),
('Roja Dove','Eliysium','Divin Asylum, FA Paris Imperium, Fragrance World'),
('Roja Dove','Enigma Pour Homme','Paradox, Rouge Perfumes'),
('Room 1015','Wavechild','Ana Abiyedh Coral, Lattafa'),
('Rosendo Mateau','No 5','Ishq Al Shuyukh Gold, Lattafa Wujood, Zimaya'),
('Shiseido','Zen','Zeno, Maison Alhambra'),
('Sol de Janeiro','Cherosia 62','Minya Green, Paris Corner'),
('Sospiro','Vibrato','Junoon Oud, Al Haramain Le Prestige Empress, Khadlaj'),
('Stéphane Humbert Lucas','God of Fire','Ophidian Mango Bliss, Paris Corner Sceptre Malachite, Mason Alhambra You Are My Fire, Zakat'),
('Stéphane Humbert Lucas','777 Venom Incarnat','You Are My Fire Rouge, Zakat'),
('Stéphane Humbert Lucas','Soleil de Jeddah Mango Kiss','Tropical Kiss, French Avenue, Fragrance World'),
('T10 The King','Taif al Emarat','Paradox Azuree, French Avenue, Fragrance World'),
('Tauer Perfumes','02 L Air du Desert Moracain','Cosmopolitan New York, Paris Corner'),
('Thameen','Carved Oud','Zaffiro Collection Crafted Oud, Maison Alhambra'),
('Thameen','Regent Leather','Zaffiro Collection Regale, Maison Alhambra'),
('Thameen','Blue Heart','Athoor Al Alam Al Raiee Lil Nisaa, Fragrance World'),
('The Spirit of Dubai','Meydan','Hypnotic Oud, Paris Corner North Stag Al Kaser, Zimaya'),
('Thomas Kosmala','No 4 Apres l Amour Elixir','No4 After Love, Fragrance World'),
('Thomas Kosmala','Apres l Amour','L Amour, MPF'),
('Tiziana Terenzi','Kirke','Jasmine Wisp, RASASI Karat, Maison Alhambra Confidential Private Gold, Lattafa'),
('Tiziana Terenzi','Porpora','Love, Chopard'),
('Tiziana Terenzi','Poggia','Atlas Coral, Asdaaf'),
('Tiziana Terenzi','Gumin','Glorify, Paris Corner Giovanni Lorenzi Lumin, French Avenue, Fragrance World'),
('Tiziana Terenzi','Andromeda','Anarch, Maison Alhambra'),
('Tiziana Terenzi','Orza','Oasis, Maison Alhambra'),
('Tiziana Terenzi','Tabit','Giovanni Lorenzi Tesoro, French Avenue, Fragrance World'),
('Tiziana Terenzi','Tuttle','Diwani Rabat, French Avenue, Fragrance World'),
('Tom Ford','Tuscan Leather','Toscano Leather, Maison Alhambra Velvet Oud, Lataffa Shalimar Oud, Ard Al Zaafaran Leather Oudh, Orientica La Yuqaqam Pour Homme, RASASI Leather Oudh, Al Haramain Roman Leather, Maison Alhambra Tuscany Leather, Fragrance World'),
('Tom Ford','Tobacco Vanille','Noble Oud, Riiffs Tobacco Touch, Maison Alhambra Amber Oud Tobacco, Al Haramain Athoor Al Alam Ameer Al Sahra, Fragrance World Vanille en Tobacco, Fragrance World'),
('Tom Ford','Oud Wood','Platinum Oud, Al Haramain Woody Oud, Maison Alhambra Private Oud, Swiss Arabian Lamasat Oud, Borouj Oud Wonder, Fragrance World Dark Aoud, Maison Alhambra'),
('Tom Ford','Bitter Peach','Bright Peach, Maison Alhambra Sutoor, Lattafa Intense Peach, Fragrance World Safari Elixir, Fragrance World'),
('Tom Ford','Rose Prick','Rose Petals, Maison Alhambra Picky Rose, Fragrance World'),
('Tom Ford','Lost Cherry','Lovely Cherry, Maison Alhambra Khaltat Night, Attar Collection Ophidian Black Cherry, Paris Corner Lush Cherry, Fragrance World Le Style Cherry Dubai to Miami, Zakat, Zoghbi Zukhruf Cherry, Zimaya'),
('Tom Ford','Ombre Leather','Rare Carbon, Afnan Amber & Leather, Maison Alhambra Velvet Oud, Lattafa Ombre Leather 33, Fragrance World Cuir Leather Parfum, Fragrance World'),
('Tom Ford','Ombre Leather (2018)','Cuir Leather, Fragrance World'),
('Tom Ford','Noir Extreme','Special Oud, Fragrance World'),
('Tom Ford','Lavendar Extreme','Lavande, Molinard (NOT ARABIC)'),
('Tom Ford','Vanilla Sex','Sehr, Lattafa'),
('Tom Ford','Costa Azzurra','Azuura, Rouge Perfumes'),
('Tom Ford','Black Orchid','Oud Jamal, Al Aneeq Oud 24 Hours, Ard Al Zaafaran La Yuqawam Pour Femme, RASASI Black Origami, Maison Alhambra Zara Man, Fragrance World'),
('Tom Ford','Black Orchid Parfum','Azara Man, Fragrance World'),
('Tom Ford','Ebene Fume','Alpha, Fragrance World Ebony Fume, Fragrance World'),
('Tom Ford','Noir De Noir','Club De Nuit Intense, Armaf'),
('Tom Ford','Metallique','Metalica, Maison Alhambra'),
('Tom Ford','Fucking Fabulous','Fabulo Intense, Maison Alhambra Fabulous Life, Fragrance World'),
('Tom Ford','Neroli Portofino','Porto Neroli, Maison Alhambra  Lazuli, Al Wataniah Wild Neroli, Orientica Portfolio Neroli Canvas, Al Haramain Safari, Fragrance World Neroli Riviera, Fragrance World'),
('Tom Ford','Cherry Smoke','Cherry Incense, Fragrance World Just (red), Fragrance World'),
('Tom Ford','Tobacco Oud','Tobacco Touch, Lattafa'),
('Tom Ford','Velvet Orchid','La Fede Code Viola Nectar, Khadlaj'),
('Tom Ford','Rose D Amalfi','Roses Amalfi, Rouge Perfumes'),
('Tom Ford','Electric Cherry','IRIDA, Frenche Avenue, Paris Corner Cherry Buzz, Fragrance World Electro Cherry, Rogue Perfumes'),
('Tom Ford','Soleil White','Le Style Soleil Dubai to Miami, Zakat, Zoghbi'),
('Tom Ford','Vanille Fatale','Hyp Vanilla, Rogue Perfumes'),
('Unique e Luxury','Crush On Me','Vintage Castle, Lattafa'),
('Valentino','Uomo Discontinue','Daarej, Rasasi Futura La Homme, Armaf'),
('Valentino','Voce Viva','Voices, Maison Alhambra'),
('Valentino','V Pour Homme','Daarej Pour Homme, RASASI'),
('Versace','Eros Flame','Versencia Rouge, Maison Alhambra'),
('Versace','Bright Crystal','Versencia Crystal, Maison Alhambra'),
('Versace','Eros','Versencia Oro, Maison Alhambra All You Need is Desire, Armaf'),
('Versace','Exciting','Versencia Essence, Maison Alhambra'),
('Versace','Crystal Noir','Versencia Noir, Maison Alhambra Ameerat Al Ehsaas, Lattafa Versus Crystal Noir, Fragrance World'),
('Versace','Versense','Versencia Essence, Maison Alhambra'),
('Versace','Dylan Blue Pour Femme','Versus Ocean Bleu Pour Femme, Fragrance World'),
('Versace','Dylan Blue Pour Homme','Versus Ocean Bleu, Fragrance World'),
('Versace','Vanitas','Derby Club House Santa Anita, Armaf'),
('Vertus','Chaos','Hayaam, Lattafa Niche Emarati'),
('Vertus','Narcos is','King of Diamonds, Fragrance World'),
('Victoria s Secret','Basic Instinct','Pure Instinct, Paris Corner, Fragrance World'),
('Victoria s Secret','Very Sexy Night','Very Velvet Noir, Maison Alhambra'),
('Victoria s Secret','Bombshell Oud','Pink Shimmer Secret Oud, Maison Alhambra Rose Seduction Secret Oud, Fragrance World'),
('Victoria s Secret','Bombshell Intense','Pink Shimmer Secret Intense, Maison Alhambra Rose Seduction Essense, Fragrance World Malikat Al Sahra, Athoor Al Alam Bombinate Intense, Paris Corner'),
('Victoria s Secret','Bombshell Celebration','Rose Seduction Secret Festive, Fragrance World'),
('Victoria s Secret','Bombshell Sundrenched','Rose Seduction Secret Sunkissed, Fragrance World'),
('Victoria s Secret','Bombshell Seduction','Rose Seduction Secret Temptation, Fragrance World'),
('Victoria s Secret','Bombshell','Pink Shimmer Secret, Maison Alhambra Rose Seduction Secret, Fragrance World'),
('Victoria s Secret','Love','Chic Velvet Pink Secret, Maison Alhambra'),
('Victoria s Secret','First Love','Chic Velvet Vert Secret, Maison Alhambra'),
('Victoria s Secret','Secret Love','Rose Seduction Secret Amor, Fragrance World'),
('Victoria s Secret','Very Sexy','Very Velvet Rouge, Maison Alhambra'),
('Victoria s Secret','Very Sexy Sea','Very Velvet Aqua, Maison Alhambra'),
('Victoria s Secret','Very Sexy Orchid','Very Velvet Orchid, Maison Alhambra'),
('Victoria s Secret','Scandalous','Rose Seduction Slanderous, Fragrance World'),
('Viktor & Rolf','Flowerbomb','Victoria Flower, Maison Alhambra Eau De Flora Mark & Victor, Fragrance World'),
('Viktor & Rolf','FlowerBomb Ruby Orchid','Victoria Flower Orchid, Maison Alhambra'),
('Viktor & Rolf','Bonbon','Boum Candy Land, Jeanne Arthes'),
('Viktor & Rolf','Spicebomb','Nuke, Fragrance World Eau De Spice Mark & Victor, Fragrance World'),
('Viktor & Rolf','Spicebomb Extreme','Eau De Spice Extreme, Fragrance World Nuke 2.0, Fragrance World'),
('Vilhelm Parfumerie','Mango Skin','Mango Delicieuse, Rogue Perfumes Mango Punch, Emir'),
('Widian','I','Wurood Boise D Arabie, Fragrance World'),
('Widian','III','Wurood Bois D Arabie, Fragrance World'),
('Widian','Limited 71','Wurood Blanc Sapphire, French Avenue, Fragrance World'),
('Xerjoff','Ivory Route','Voux Spices, Emir'),
('Xerjoff','Erba Pura','Voux Turquoise, Emir, Paris Corner Amber Oud Gold Edition, Al Haramain Shaghaf Oud Ahmar, Swiss Arabian La Yuqawam Jasmine Wisp, Rasasi Ana Abiyedh, Lattafa Royal Amber, Al Haramain Philos Pura, Maison Alhambra Durrat Al Aroos, Al Wataniah Amber is Great, Zimaya Rabab, Zimaya Xclusif Oud Classic, Orientica Amber D Or, French Avenue, Fragrance World'),
('Xerjoff','Naxos','Voux Elegante, Emir (Paris Corner)'),
('Xerjoff','Dama Bianca','Janoon Noir, Al Haramain Ishraq, Orientica'),
('Xerjoff','More Than Words','Maahir, Lattafa'),
('Xerjoff','Casamorati La Tosca','Casamorando La Bruta, Fragrance World'),
('Xerjoff','La Capitale','Kashaf, Lattafa'),
('Xerjoff','Alexandria II','Prestige Portrait Oud, Arabiyat'),
('Xerjoff','Casamorati 1888','Casamorando 1988, Fragrance World'),
('Xerjoff','Accento','Rebab Gems, Zimaya Philos Centro, Maison Alhambra'),
('Xerjoff','Opera','Philos Opus Noir, Maison Alhambra'),
('Xerjoff','Accent','Rebab Gems, Zimaya'),
('Xerjoff','Lira',''),
('Xerjoff','Italica','Voux Patrisserie, Emir'),
('Xerjoff','Coro','Belle Dolce, Fragrance World'),
('YSL','L Homme','L Uomo, Fragrance World'),
('YSL','La Nuit De L homme Bleu Electrique','Ejaazi Silver Intense, Lattafa Jack of Clubs, Fragrance World Scudo Electrique, Fragrance World All You Need Is Love, Armaf'),
('YSL','La Nuit De l Homme','L Uomo The Night Edition, Fragrance World'),
('YSL','L Homme Intense','Niche Platinum, Armaf'),
('YSL','Tuxedo','Kismet, Alhambra Suits Eau De Parfum, Fragrance World The Tux, Maison Alhambra Ighwa, Fragrance World Rifaaqat Adorn, Paris Corner TAG Uomo Nero, Armaf'),
('YSL','Y','Fakhar, Lattafa Fakhar Black, Lattafa YEAH!, Maison Alhambra Final Edition, Lattafa Al Tayoor Concentrated, Lattafa Sheikh Shuyukh Final Edition, Lattafa Why, Privezarah, Paris Corner'),
('YSL','Y Le','F Le Parfum, Fragrance World'),
('YSL','Y EDT','Baroon, Al Rehab'),
('YSL','Baby cat','Rifaaqat Edp Emir Series Nayel Queen, Arabiyat Prestige Spice + Vanilla, Rogue Perfumes'),
('YSL','Supreme Bouquet','Bouquet Supreme Gold, White Oud Perfumes'),
('YSL','Mon Paris','My Party, Maison Alhambra'),
('YSL','Black Opium','Opera Noir, Mason Alhambra'),
('YSL','Rouge Velours','Velvet Rouge, Fragrance World Athoor Al Alam Anaqeed Rouge, Fragrance World'),
('YSL','Libre','Libbra, Maison Alhambra Leonie, Maison Alhambra'),
('YSL','Libre Intense','Tharwah Gold, Lattafa Freedom Intense, MPF'),
('YSL','Manifesto','Sheikha, Orientica'),
('YSL','Manifesto l Elixer','Katarina Light Blue, Armaf'),
('YSL','Belle d Opium','Roohy Tehbak, RASASI'),
('YSL','M7','Niche Oud, Armaf'),
('YSL','Rive Gauche Pour Homme Intense','Niche Black Onyx, Armaf'),
('Zielinski & Rozen','Black Pepper & Amber','Amber and Neroli, Fragrance World');
